import { useAuthenticatedUser, useLogin, useSignup } from "./auth";
import {
	useApplications,
	useApproveTutor,
	useApprovedTutors,
	useBookSession,
	usePendingApplications,
	useRejectTutor,
	useResetDemoData,
	useSessions,
	useSubmitTutorApplication,
	useTutorList,
	useTutors,
	useUpdateTutorAvailability,
} from "./tutor";
export const hooks = {
	useLogin,
	useSignup,
	useAuthenticatedUser,
	useTutors,
	useTutorList,
	useSessions,
	useApplications,
	useApprovedTutors,
	usePendingApplications,
	useSubmitTutorApplication,
	useApproveTutor,
	useRejectTutor,
	useBookSession,
	useUpdateTutorAvailability,
	useResetDemoData,
};
